### ISSUE TITLE
'Minimal density' setting gives not the expected result.

### ISSUE THREAD

**Issue by joris57** [MosaicManufacturing/canvas-issues#132] opened 2019-12-22 10:42 UTC
The image below shows a single layer of a multi-color print (2 stacked cubes) and the corresponding purge tower. As only one color is printed at any time, I would expect the purge tower to be printed at minimal infill density.

Both the 'minimal density' (of the purge tower) and the 'infill density' of the object were set at 5%. I would therefore expect a similar amount of infill when comparing the object to the purge tower. This is obviously not the case.

Also there is NO difference between a purge tower with 5% minimal density (1st image) and 10% minimal density (2nd image). For comparison purposes, also the object infill was changed from 5% to 10%.

 
![image](https://user-images.githubusercontent.com/22101914/71320698-4b559c80-24af-11ea-93cd-0574b19336d6.png)

![image](https://user-images.githubusercontent.com/22101914/71320713-9c659080-24af-11ea-8508-4cb87d0b9cc7.png)

**Comment by brandonbloch** [comment] 2020-01-02 16:32
Hi @joris57,

This is definitely confusing but is not actually a bug. As mentioned in [this discussion](https://github.com/MosaicManufacturing/canvas-issues/issues/130#issuecomment-566253825), sparse tower layers have a minimum of 20 mm extrusion, which is currently a hard requirement for accessory mode. At your minimum density setting, the tower layer would have much less than this amount, which is why the density needs to be raised. Please note that removing this limitation for connected mode prints is on our to-do list, but will require us to validate that print calibration is unaffected by the change.

You can see this by using the same tower settings but causing the tower to be bigger (via more colors on a single layer). This print goes from 1 color to 2:

![Screen Shot 2020-01-02 at 11 27 38 AM](https://user-images.githubusercontent.com/217964/71678477-40262a80-2d53-11ea-8973-7298454eb53f.png)

While this print goes from 1 color to 3:

![Screen Shot 2020-01-02 at 11 28 06 AM](https://user-images.githubusercontent.com/217964/71678492-4c11ec80-2d53-11ea-9630-a34c8e53da05.png)

You can see that the tower has become physically larger, but the density of sparse layers has decreased accordingly. This tower has a 5% minimum density but in neither case can it actually go that low.

I'm leaving this issue open as this is a change we'd like to make; however, since it's currently the intended behaviour I'll mark it as an enhancement rather than a bug.

Cheers,
Brandon

**Comment by brandonbloch** [comment] 2020-02-10 20:07
Hi again,

Thank you for your patience! This behaviour has been changed when running in connected mode—there is now no minimum extrusion for tower layers, which means that layers without any transitions will always respect your minimum density setting. The change is live, and so I'm closing this issue. Please let us know if you experience any issues with the change!

Cheers,
Brandon

**Closed as completed by brandonbloch** 2020-02-10 20:07 UTC
Labels: enhancement
