### ISSUE TITLE
Custom supports, tree supports, variable infill %

### ISSUE THREAD

**Issue by Phoenix54** [MosaicManufacturing/canvas-issues#124] opened 2019-11-13 20:33 UTC
Custom supports and tree supports would help with material saving on areas where supports are not needed and areas that need supports you can add them. Variable infill would be good for large prints that dont need a whole lot of infill but need support for the top layers.

**Comment by brandonbloch** [comment] 2019-11-25 21:15
Closing as duplicate of #81 for custom supports. As for the variable infill, CANVAS already has this behaviour (controlled by "Semi-solid layers below top surfaces" under General > Solid Layers. When enabled, the final infill layers are made 50% dense, allowing you to use very low infill densities without needing very many solid top layers.

As an example, here is a cube sliced with the setting turned on (looking only at the topmost few layers from below):

![Screen Shot 2019-11-25 at 4 12 23 PM](https://user-images.githubusercontent.com/217964/69578412-6f9c8700-0f9e-11ea-89d5-e302a7afbfca.png)

If you're aware of this functionality but are looking to see it extended in some way, please feel free to re-open this issue or create a new feature request.

Cheers,
Brandon

**Closed as completed by brandonbloch** 2019-11-25 21:15 UTC
