### ISSUE TITLE
Transition tower off bed when changing settings

### ISSUE THREAD

**Issue by binux14** [MosaicManufacturing/canvas-issues#39] opened 2018-10-29 16:02 UTC
**Describe the bug**
When you open a multi-material project and go to Settings/Style Settings/Transition/Transition Method and you change it, when you go back to "Transition tower" method the tower on the visualizer moves out of the bed. I think the center of the towers moves to the origin.

**To Reproduce**
1. Open a multi-material project
2. Click on the "Settings" tab
3. Click on "Transition"
4. Change the Transition Method to "Side transitioning" or "No handling"
5. Change the Transition Method back to "Transition tower"
6. The tower will now be off the bed.

**Expected behavior**
The tower should be in the same place as before changing the method.

**Screenshots**
![image](https://user-images.githubusercontent.com/42580486/47662893-382c9280-db72-11e8-8edc-76d1306b7316.png)
![image](https://user-images.githubusercontent.com/42580486/47662944-4ed2e980-db72-11e8-9f36-ffdee6d9a17f.png)

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100

**Comment by brandonbloch** [comment] 2018-10-29 22:29
Thanks @binux14, this is a known issue and we are actively working on a solution. The full auto-arrange solves this; however, this is slow and forces us to interrupt your coloring flow with a loading spinner. We want to come up with something that works as close to auto-arranging as possible without the flow interruption, to get the best of both worlds. We will update this thread as progress is made!

**Comment by brandonbloch** [comment] 2018-11-21 14:46
Closing as duplicate of #32

**Closed as completed by brandonbloch** 2018-11-21 14:46 UTC
Labels: bug
