### ISSUE TITLE
Reducing waste filament for multicolor prints

### ISSUE THREAD

**Issue by Cruzen** [MosaicManufacturing/canvas-issues#86] opened 2019-02-20 01:36 UTC
I was just thinking that eventually there should be an option when printing with the P2 / P2P, to make a second random color model instead of a waste block.  you could tell the software to duplicate the model you are printing with the waste so the colors in it would be random rainbow pattern but you would have a second  useable model.  you could even pick a different model and tell it to size it appropriately & print it with the waste only.  I just bought a roll of rainbow filament for just that effect, this would make that unnecessary.  I don't think people would use it every time but i think it would be used quite often and you would not have to throw away anywhere near as much filament.  Also people who are making prints to sell could make twice as many and 1\2 would be the colors you picked and the other 1\2 would be random colors but sellable.  I think this idea should have some serious consideration.

Thanks
Tony Sexsmith

**Comment by brandonbloch** [comment] 2019-02-20 22:52
Absolutely a good idea, and something we will be working on in the coming months. In fact this feature has already been requested, so I'm closing this as a duplicate of #67.

Cheers,
Brandon

**Closed as completed by brandonbloch** 2019-02-20 22:52 UTC
Labels: duplicate
