### ISSUE TITLE
Cycling print cooling fan

### ISSUE THREAD

**Issue by uilleann** [MosaicManufacturing/canvas-issues#106] opened 2019-06-29 17:09 UTC
**Describe the bug**
Printer Cooling Fan is Cycling.  Gcode generated by Canvas has regular M107 commands in "destring" operation.

**To Reproduce**
Start print. after first layer you can see the extruder temp cycle from 202-215C on a set point of 210C.  In cavas the fan is set to be 100% after 1st layer.  Its PLA  at .2mm, .15 infil with retraction on

**Expected behavior**
Expected fan to be on all the time with a steady extruder temp
[bases4.gcode.txt](https://github.com/MosaicManufacturing/canvas-issues/files/3342155/bases4.gcode.txt)

**Screenshots**

**Operating System (please complete the following information):**
 - OS: Sierra
 - Browser Safari

**Additional context**
I had an earlier print with the exact same design but some of the settings (layer thickness, speed) were different.  I went into this current print on canvas and changed the settings to reflect the earlier print that had no fan cycling.  Did the slice.  Before the change this gcode had 3 incidents of M107, and now its over 800 M107's.  I think there is an issue at your end.

**Comment by brandonbloch** [comment] 2019-07-05 14:40
Hi @uilleann,

This definitely sounds like a bug but I just want to confirm whether you have "Perimeter fan speed" set to "Auto" or a manual value. Would you mind sharing the project (and checking all boxes) so we can try to reproduce the issue?

**Comment by brandonbloch** [comment] 2019-07-05 16:28
After investigating #104, this may be a potential duplicate of that issue. It should be resolved and the fix is being pushed out at the moment, so I'd actually suggest to simply try re-slicing the project in about an hour and see if the correct fan commands are being inserted.

**Comment by uilleann** [comment] 2019-07-05 18:39
It is working now.... Thanks!

**Comment by brandonbloch** [comment] 2019-07-05 19:20
Fantastic, glad to hear that!

**Closed as completed by brandonbloch** 2019-07-05 19:20 UTC
Labels: bug
