### ISSUE TITLE
Feature Request:  Supports on build plate only

### ISSUE THREAD

**Issue by debk3141** [MosaicManufacturing/canvas-issues#127] opened 2019-12-05 00:08 UTC
It would be very useful to be able to generate support on build plate only instead of everywhere like it is now.  This works very well on Prusa slicer

**Comment by brandonbloch** [comment] 2019-12-12 21:43
Closing as duplicate of #81 (specifically [this comment](https://github.com/MosaicManufacturing/canvas-issues/issues/81#issuecomment-466679164)). Please feel free to thumbs-up or comment on the thread there.

Cheers,
Brandon

**Closed as completed by brandonbloch** 2019-12-12 21:43 UTC
