### ISSUE TITLE
Infill added where none should be.

### ISSUE THREAD

**Issue by cephdon** [MosaicManufacturing/canvas-issues#175] opened 2020-07-25 17:17 UTC
I sliced the attached STL and didn't notice that the resulting gcode included infill where a hole should be.
In fact, this file will slice properly on Cura, but it has this weird effect on Canvas.
To help you resolve the issue, I have attached the STL, and resulting gcode file and my infill settings.

[Mask_body_L_wide.zip](https://github.com/MosaicManufacturing/canvas-issues/files/4976044/Mask_body_L_wide.zip)
[Mask-body-L-wide-2.zip](https://github.com/MosaicManufacturing/canvas-issues/files/4976045/Mask-body-L-wide-2.zip)
![Infill_Settings](https://user-images.githubusercontent.com/5387229/88462409-17918980-ce79-11ea-8c05-17819ad87fbe.PNG)

**Comment by cephdon** [comment] 2020-07-25 17:20
Here are the images of the correct slicing and incorrect slicing between layers 20 and 21.
![Incorrect_Slicing at layer 21](https://user-images.githubusercontent.com/5387229/88462483-9090e100-ce79-11ea-9ba8-195083657ae6.PNG)
![Correct_Slicing at layer 20](https://user-images.githubusercontent.com/5387229/88462486-9686c200-ce79-11ea-8f78-5791dbd43b57.PNG)

**Comment by brandonbloch** [comment] 2020-11-13 20:28
Hi @cephdon, sorry about the delay here. It looks like this was caused by a mesh error (confirmed with Simplify3D's analysis tools) which proved a bit tricky to repair, but here is a repaired file that I got to slice without any issues:

[Mask_body_L_wide_fixed.stl.zip](https://github.com/MosaicManufacturing/canvas-issues/files/5539139/Mask_body_L_wide_fixed.stl.zip)

<img width="599" alt="Screen Shot 2020-11-13 at 3 25 24 PM" src="https://user-images.githubusercontent.com/217964/99117856-76b01100-25c4-11eb-9969-3852aa04ae6c.png">

I'm closing the issue as it has a resolution. However, if you're interested in mesh analysis and/or repair as a feature in CANVAS, please feel free to open a feature request!

**Closed as completed by brandonbloch** 2020-11-13 20:28 UTC
Labels: bug
