### ISSUE TITLE
Mirror Mesh capability

### ISSUE THREAD

**Issue by trevorray51** [MosaicManufacturing/canvas-issues#23] opened 2018-09-18 01:24 UTC
One feature that I would like to request is the ability to mirror mesh like in S3D. I have a printer that requires me to mirror the Y-axis mesh any model that is not symmetrical. The alternative if this feature is not available requires me to take the model in S3D, mirror the y mesh, save as STL, and then upload it to Canvas3D. For some models this is not a problem but when it comes to multiple models issues can arise. Thank you.

**Comment by mikemklee** [comment] 2018-10-22 20:16
@trevorray51 Thank you for your feedback! This feature is now implemented in the most recent version of CANVAS. You will be able to find a button to flip selected models on the `Rotation` tool while you are on the `Place` step. If you wanted to create a mirrored duplicate of a model, then you could first duplicate the model then use the flip button to create meshes that are "mirrored". We hope that this new change will enhance your experience with CANVAS. Please feel free to submit any other issues as you encounter them and we will be happy to respond!

**Closed as completed** 2018-10-22 20:19 UTC
Labels: enhancement
