### ISSUE TITLE
Slicing keeps failing

### ISSUE THREAD

**Issue by onxygit** [MosaicManufacturing/canvas-issues#138] opened 2020-02-24 07:22 UTC
Not sure why, but slicing this model (originally from thingiverse (https://www.thingiverse.com/thing:3527243) continually fails. There's no debug info shared. Could it be my profile? Settings? The model itself?

https://share.canvas3d.io/projects/49d0696b4637af4a1572017e98a940d6

Also, just tried to import from the shared urll and got this:

![Screen Shot 2020-02-23 at 11 23 49 PM](https://user-images.githubusercontent.com/47630447/75134616-b11efa00-5693-11ea-9dca-27fcd42a1787.png)

**Comment by brandonbloch** [comment] 2020-02-24 15:53
Hi there,

Sorry you're running into this issue! Upon further investigation, both of these issues are caused by the STL files themselves. They contain some non-standard formatting, which our converter is currently handling incorrectly, and the resulting partially-broken geometry can't handled correctly during slicing, auto-arrange, etc.

We're working on a fix and hope to have something released today or tomorrow. In the meantime, here are the same STLs without the formatting quirks. Uploading these ones instead of the Thingiverse files should avoid the issue while we work on a fix.

Cheers,
Brandon

**Comment by brandonbloch** [comment] 2020-02-24 15:53
[Mandala-Fixed.zip](https://github.com/MosaicManufacturing/canvas-issues/files/4245410/Mandala-Fixed.zip)

**Comment by onxygit** [comment] 2020-02-25 06:40
Wow thanks for the quick response, and for addressing my issue! :)

**Comment by brandonbloch** [comment] 2020-02-26 15:48
No problem! The fix for this bug has been released and the original models should no longer cause any problems.

Cheers,
Brandon

**Closed as completed by brandonbloch** 2020-02-26 15:48 UTC
Labels: bug

**Comment by onxygit** [comment] 2020-04-13 01:16
Hey again, so I updated my design based on the model you fixed for me (see https://canvas3d.io/slicer/04520aa9c97e8cf0b9bdd85c1ca0589a). I tried printing, and it looked like the filament was generating correctly, but that my printer made it part way (I'd say about a third) and then stopped. I tried printing the .gx file (i have a FlashForge Adventurer 3 lite) with one solid color filament, bypassing the Palette, and I got the same result, so I don't think it's a splicing problem, but it appears to be a problem with the .gx file canvas generated. I'm attaching a pic of the solid color print, the generated .gx file, and a screenshot of the flashforge slicer viewing the .gx file. Notice that there's a visible difference between the bottom 1/3 of the print and the layers above. Notice also that this happens at around layer 18,000 -- I'm not sure why it's printing so many layers, since I chose a .2mm layer height. 
![Screen Shot 2020-04-12 at 6 06 56 PM](https://user-images.githubusercontent.com/47630447/79084577-5ac05600-7ce9-11ea-8f18-dd913fc2e9cb.png)
![Screen Shot 2020-04-12 at 6 13 08 PM](https://user-images.githubusercontent.com/47630447/79084581-5d22b000-7ce9-11ea-9ec1-679f3d2e4ce3.png)

[Green-2 (1).zip](https://github.com/MosaicManufacturing/canvas-issues/files/4467555/Green-2.1.zip)
![unnamed-3](https://user-images.githubusercontent.com/47630447/79084629-a07d1e80-7ce9-11ea-89e6-baaf12697c89.jpg)

**Comment by onxygit** [comment] 2020-04-13 01:18
![Screen Shot 2020-04-12 at 6 17 17 PM](https://user-images.githubusercontent.com/47630447/79084675-e3d78d00-7ce9-11ea-9028-2032bc0034e9.png)
Here's a closeup from the slicer view... it looks like there's a pronounced difference in the bottom, then an air gap, and then some spaced out layers on the top!

**Comment by onxygit** [comment] 2020-04-13 08:07
![Screen Shot 2020-04-13 at 1 06 03 AM](https://user-images.githubusercontent.com/47630447/79104241-089c2680-7d23-11ea-96c7-2c8587b7fb20.png)
Yeah, there's only like 80 something layers in Canvas and tens of thousands read by FlashPrint, and Chroma just gives me this :/

**Comment by brandonbloch** [comment] 2020-04-14 12:23
Hey there, sorry about this! I extracted the G-code out of the .gx file you provided and opened it with Simplify3D's visualizer. The large number of layers I'm not so sure about, but it looks to be a UI/parsing issue rather than a G-code level one as S3D lists a much more reasonable 128 layers (text box at bottom right):

<img width="1030" alt="Screen Shot 2020-04-14 at 8 06 55 AM" src="https://user-images.githubusercontent.com/217964/79223684-cd375000-7e27-11ea-923e-14c7e00bf659.png">

As for the gaps (as well as the very strange extrusion in the print), it appears that the tool I used to fix the STLs affected the relative alignment of the models, and they need some manual adjustment aside from just aligning + grouping them. Really sorry about that, I was sure my tool maintained their original positions. You can see the gaps, and floating bodies from the mis-alignment, more clearly here:

<img width="966" alt="Screen Shot 2020-04-14 at 8 11 29 AM" src="https://user-images.githubusercontent.com/217964/79223800-040d6600-7e28-11ea-8fb7-13a59a6a8303.png">

In general, scrolling through the layers in CANVAS' visualizer can help a lot to spot issues with strange extrusion, especially due to mesh issues resulting in solid internal regions:

<img width="903" alt="Screen Shot 2020-04-14 at 8 18 30 AM" src="https://user-images.githubusercontent.com/217964/79224089-8a29ac80-7e28-11ea-9361-d4f681138d20.png">

Since the issue with the original models has been fixed, I would recommend using them instead of my modified ones—this is generally easier than accurately aligning all the models in X/Y/Z by hand. That said, this model in particular is especially problematic and CANVAS does not currently do any built-in mesh repair or analysis, so it may be worth investigating improving these STLs. Mesh analysis/repair are on our radar but please feel free to open a new issue if you'd like to formally request it.

Finally, Chroma only opens and previews multi-extruder files, such as multi-process .gx files generated by Simplify3D, but not the single-extruder G-code CANVAS generates.

I hope that helps! Please let us know if you have any further issues or questions.

Cheers,
Brandon
